//! Small, native-only credential boundary for secrets owned by the app.
//!
//! The renderer never writes bearer tokens to localStorage or the connector
//! registry. These commands accept only a bounded opaque key and delegate the
//! value to the operating system's credential store.

const SERVICE: &str = "com.muse.desktop.mcp";

/// Validate a storage key before it reaches the platform credential store.
/// Keys are generated by the renderer from connector ids and are deliberately
/// restricted so a malformed request cannot create arbitrary store metadata.
pub fn validate_key(key: &str) -> Result<&str, String> {
    let key = key.trim();
    if key.is_empty() || key.len() > 180 {
        return Err("secure storage key is invalid".to_string());
    }
    if !key
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b':' | b'_' | b'-'))
    {
        return Err("secure storage key is invalid".to_string());
    }
    Ok(key)
}

fn entry(key: &str) -> Result<keyring::Entry, String> {
    let key = validate_key(key)?;
    keyring::Entry::new(SERVICE, key).map_err(|_| "native secure storage is unavailable".to_string())
}

/// Store a secret in the OS credential manager. The secret is never returned
/// in an error and is not logged by this boundary.
pub fn set(key: &str, secret: &str) -> Result<(), String> {
    if secret.is_empty() || secret.len() > 64 * 1024 {
        return Err("secure storage value is invalid".to_string());
    }
    entry(key)?
        .set_password(secret)
        .map_err(|_| "native secure storage could not save the credential".to_string())
}

/// Read a secret. A missing credential is a normal disconnected state.
pub fn get(key: &str) -> Result<Option<String>, String> {
    match entry(key)?.get_password() {
        Ok(secret) => Ok(Some(secret)),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(_) => Err("native secure storage could not read the credential".to_string()),
    }
}

/// Remove a secret. Deleting an already absent value is idempotent.
pub fn remove(key: &str) -> Result<(), String> {
    match entry(key)?.delete_credential() {
        Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
        Err(_) => Err("native secure storage could not remove the credential".to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::validate_key;

    #[test]
    fn storage_keys_are_bounded_and_metadata_safe() {
        assert_eq!(validate_key("remote-mcp:remote-github"), Ok("remote-mcp:remote-github"));
        assert!(validate_key("").is_err());
        assert!(validate_key("remote/mcp").is_err());
        assert!(validate_key(&"x".repeat(181)).is_err());
    }
}
